### ISSUE TITLE
PHP Fatal error:  Maximum execution time of 30 seconds exceeded ...assets/mpdf/mpdf.php

### ISSUE THREAD

**Issue by chrisforduk** [tarpey/edocs#1]
![image](https://cloud.githubusercontent.com/assets/1437235/6653712/3893e554-ca94-11e4-9d41-1cbc9dc08591.png)

![image](https://cloud.githubusercontent.com/assets/1437235/6653751/c4ac53d6-ca95-11e4-8389-3d61b21d7e41.png)

You could increase the time:
ini_set('max_execution_time', 3600); // 1 hour

But probably need to find a solution to streamline /adjust settings in mpdf.php

**Comment by tarpey** [comment]
Fixed in b7ad08f9c46a90b3562252eb20c10e17f772411c.
