### ISSUE TITLE
Header expects parameter 3 to be long.

### ISSUE THREAD

**Issue by chrisforduk** [tarpey/edocs#2]
![image](https://cloud.githubusercontent.com/assets/1437235/6653783/8c3869f8-ca96-11e4-9ca6-f225b4a5e488.png)

This occurs on every page.

I believe due to the 404 page

**Comment by chrisforduk** [comment]
This seems to be the fix:


<?php
	wp_redirect(get_option('edocs_options')['redirect'], 301);
	exit;

**Comment by tarpey** [comment]
Fixed in dbafeca4c96a92a8effc9bab8d494d90d9a1db9d
