### ISSUE TITLE
Header download link

### ISSUE THREAD

**Issue by chrisforduk** [tarpey/edocs#5]
If wordpress is installed in a folder the download link doesn't work.

I suggest tweaking header.php

href="<?php echo dirname(get_bloginfo('url')).'/download/'.$pdf_file;?>"><i class="fa fa-cloud-download"></i> Download

becomes

 href="<?php echo get_bloginfo('url').'/download/'.$pdf_file;?>"><i class="fa fa-cloud-download"></i> Download

**Comment by tarpey** [comment]
Fixed in feb46c7c88dec8a9d935b4b299862bbfa53b9d77.
